import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a>
          kelompok 4
        </a>
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/pemakaianair" style={{ color: "#87CEFA", textDecoration: "none" }}>
            PemakaianAir
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/batterystatus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BatteryStatus
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/status" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Status
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/dashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Dashboard
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
